---
- name: Task Failure Excercise
  hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Install {{ web_package }} package
      ansible.builtin.dnf:
        name: "{{ web_package }}"
        state: present

    - name: Install "{{ db_package }}"
      ansible.builtin.df:
        name: "{{ db_package }}"
        state: present

